const data = [
  {
    id: 1,
    category: "uiux",
    image: "/assets/project1.jpg",
    title: "Project Title One (UIUX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 2,
    category: "frontend",
    image: "/assets/project2.jpg",
    title: "Project Title Two (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 3,
    category: "frontend",
    image: "/assets/project3.jpg",
    title: "Project Title Three (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 4,
    category: "uiux",
    image: "/assets/project4.jpg",
    title: "Project Title Four (UIUX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 5,
    category: "uiux",
    image: "/assets/project5.jpg",
    title: "Project Title Five (UIUX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! ",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 6,
    category: "frontend",
    image: "/assets/project6.jpg",
    title: "Project Title Six (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 7,
    category: "frontend",
    image: "/assets/project7.jpg",
    title: "Project Title Seven (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 8,
    category: "backend",
    image: "/assets/project8.jpg",
    title: "Project Title Eight (Backend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
  {
    id: 9,
    category: "frontend",
    image: "/assets/project9.jpg",
    title: "Project Title Nine (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://github.com/mansourlotfi",
    github: "https://github.com/mansourlotfi",
  },
];

export default data;
